### ISSUE TITLE
Server Crash/Freeze from exception

### ISSUE THREAD

**Issue by DokiDerg** [kyleseven/ConsoleReader#8]
**Describe the bug**
Server crashes/freezes after a error in the plugin, i belive it was from my config having invalid regex and forgetting a \ before the -, but still is an issue that should just error the plugin rather than crashing the server

**To Reproduce**
1. Join server, geyser seems to be what set it off, i had the litteral "[Geyser-Spigot]" instead of a regex safe version
2. Enable CR
3. Leave the server?

**Expected behavior**
A try/catch with `exception.printStackTrace();` instead of throwing an exception

**Screenshots**
Check additional context

**Server Information**
 - Version: Paper 196, MC 1.20.1, API 1.20.1-R0.1-SNAPSHOT Git 773dd72
 - Plugin Version: 1.5.4
 - Plugin List:

```
AdvancedHelp
AntiPopup
BisectHosting
ChestCleaner
ChestShop
Chunky
ConsoleReader
ConsoleSpamFix
CoreProtect
DokiDergPlugin
Duels
dynmap
emotecraft
Essentials
EssentialsAntiBuild
EssentialsChat
EssentialsProtect
FastAsyncWorldEdit
floodgate
Geyser-Spigot
GeyserSkinManager
GeyserUpdater
GrimAC
GSit
HeadAtDeath
IllegalStack
IridiumSkyblock
LibsDisguises
LuckPerms
Maintenance
Multiverse-Core
Multiverse-Inventories
Multiverse-NetherPortals
Multiverse-Portals
MyCommand
NBTAPI
Orebfuscator
PacketWrapper
Pl-Hide-Pro
PlaceholderAPI
```

**Additional context**
```
[31.10 09:38:25] [Disconnect] DokiDerg has disconnected, reasonDisconnected
[31.10 09:38:25] [Server] 2023-10-11:38:25,728 Server thread ERROR An exception occurred processing Appender ConsoleReader-fea56ef2-dc85-4bb4-9b7c-35d22a4f6e11 java.util.regex.PatternSyntaxException: Illegal character range near index 8
[31.10 09:38:25] [Server] [Geyser-Spigot] [mcxboxbroadcast] [Primary Session] Connection to websocket lost, re-creating session...
[31.10 09:38:25] [Server]         ^
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.range(Pattern.java:2820)
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.clazz(Pattern.java:2708)
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2139)
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
[31.10 09:38:25] [Server] 	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
[31.10 09:38:25] [Server] 	at ConsoleReader-1.5.4-ALPHA.jar//me.kyleseven.consolereader.kotlin.text.Regex.<init>(Regex.kt:89)
[31.10 09:38:25] [Server] 	at ConsoleReader-1.5.4-ALPHA.jar//me.kyleseven.consolereader.logreader.LogAppender.append(LogAppender.kt:69)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.core.Logger.log(Logger.java:162)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2040)
[31.10 09:38:25] [Server] 	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1907)
[31.10 09:38:25] [Server] 	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:185)
[31.10 09:38:25] [Server] 	at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2169)
[31.10 09:38:25] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2157)
[31.10 09:38:25] [Server] 	at net.minecraft.network.NetworkManager.m(NetworkManager.java:818)
[31.10 09:38:25] [Server] 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:254)
[31.10 09:38:25] [Server] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1586)
[31.10 09:38:25] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[31.10 09:38:25] [Server] 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[31.10 09:38:25] [Server] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[31.10 09:38:25] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[31.10 09:38:25] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)
[31.10 09:38:25] [Server] 2023-10-11:38:25,733 Server thread ERROR An exception occurred processing Appender ConsoleReader-fea56ef2-dc85-4bb4-9b7c-35d22a4f6e11 java.util.regex.PatternSyntaxException: Illegal character range near index 8```

**Comment by kyleseven** [comment]
Thanks for the report, I've implemented a fix and will be releasing it as v1.5.5 shortly.
